<img src='img/images.jpeg' />


 <span style='color:blue'> NumPy </span> is a general purpose array processing package.It provides a high performance multidimentional array object and tools for working with these arrays.It is the fundamental package for scientific computing with python.
## Features of Numpy:-
- A powerful N-dimentional array object.
- Sophisticated (broadcasting) functions.
- Tools for integrating C/C++ and Fortran code.
- Useful linear algebra,Fourier transform and random number capabilities.

## Advantages of Numpy over regular Python lists:-
- Numpy is more **memory efficient** than regular python list.
- Numpy is more **covenient** than python list.
- Numpy provides a lot of **vector and matrix operation** for free which sometimes allow one to avoid uncecessary work.
- Numpy array is **10x faster** than regular python lists.

In [63]:
#import numpy package
import numpy as np

## Array Creation using Numpy
**There are 5 general mechanisms for creating arrays in Numpy:**
1. Conversion from other Python structures (e.g., lists, tuples)
2. Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)
3. Reading arrays from disk, either from standard or custom formats.
4. Creating arrays from raw bytes through the use of strings or buffers.
5. Use of special library functions (e.g., random).

### Array Creation:- Conversion from other Python structures (e.g., lists, tuples)

In [68]:
# creating 1D array
myarr=np.array([2,3,5,6])
myarr

array([2, 3, 5, 6])

In [69]:
#Creating 2d array
x=np.array([[2,3,4]])
x

array([[2, 3, 4]])

In [28]:
# creating arrary using tuple and list 
y=np.array([[1,2.0],[0,0],(1+1j,3.)]) 

In [23]:
y

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

###  <span style='color:blue'> Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)</spna>
NumPy has built-in functions for creating arrays from scratch such as:
1. **zeros(shape)** will create an array filled with 0 values with the specified shape. The default dtype is float64.
2. **ones(shape)** will create an array filled with 1 values. It is identical to zeros in all other respects.
3. **arange()** will create arrays with regularly incrementing values.
4. **linspace()** will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values. 

### using zeros()

In [32]:
# gives (3,4) shape array with value zero and it's type is float
arr=np.zeros((3,4)) 
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
 #insert value
arr[2,3]=3.5  
arr

array([[0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 3.5]])

### using ones()

In [39]:
#gives (2,3) shape array with value one and it's type is float
a=np.ones((2,3)) 
a

array([[1., 1., 1.],
       [1., 1., 1.]])

### using arange()

In [41]:
 # creating 1d array from 0-10
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# creatig 1d array from 2 to 3 which difference .1
np.arange(2, 3, 0.1) 

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

### using  linspace()

In [43]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

### Some other NumPy  built-in functions for creating arrays 
- empty()
- identity()

In [44]:
np.empty((2,3)) #giving array with random value

array([[1. , 1.6, 2.2],
       [2.8, 3.4, 4. ]])

In [45]:
np.identity(5) #for creating identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Creating array using special library functions (e.g., random).


#### Random sampling with float values
-np.random.random()

In [187]:
#Creating 1-D array
out_arr=np.random.random(size=3)
print('1D array filled with random floats: ',out_arr)

1D array filled with random floats:  [0.87994498 0.19761757 0.5230019 ]


In [190]:
#creating 2-D array
out_arr=np.random.random(size=(2,4))
print('2D array filled with random floats: ',out_arr)

2D array filled with random floats:  [[0.25727793 0.44616548 0.86677301 0.95674354]
 [0.66901285 0.20986148 0.42707955 0.87131262]]


In [192]:
#Creating 3-D array
out_arr=np.random.random(size=(2,3,2))
print('3D array filled with random floats: ',out_arr)

3D array filled with random floats:  [[[0.84608834 0.09268362]
  [0.92327891 0.59210469]
  [0.51990464 0.98883379]]

 [[0.74947522 0.07986873]
  [0.08258312 0.1245685 ]
  [0.26729399 0.52283808]]]


### Random sampling with integer with value
- np.random.randint()

In [197]:
x=np.random.randint(10,size=5) # 10 defines the range 0f value here(1-10)
print('1D array filled with random integers: ',x)

1D array filled with random integers:  [3 5 3 1 5]


In [201]:
x=np.random.randint(100,size=(3,4))
print('2D array filled with random integers: \n',x)

2D array filled with random integers: 
 [[57 55 69 53]
 [96 96 48 25]
 [54 46 68 19]]


In [202]:
x=np.random.randint(100,size=(3,4,3))
print('3D array filled with random integers: \n',x)

3D array filled with random integers: 
 [[[54  9 13]
  [96 58 92]
  [46 96 78]
  [ 0 71 67]]

 [[57 83  1]
  [65 77 89]
  [60 35 88]
  [48 94  7]]

 [[92 13 80]
  [90 87 29]
  [88 81 81]
  [86 60 25]]]


# Some Basic Attributes of Numpy array
- "ndim" attribute
- "shape" attribute
- "size" attribute
- "dtype" attribute
- "itemsize" attribute


In [83]:
towd_ar=np.array([[23,4,5],[2,3,4]])
ar

array([[23,  4,  5],
       [ 2,  3,  4]])

In [84]:
# ndarry.ndim  represents the number of dimension
towd_ar.ndim

2

In [85]:
# ndarray.shape  represents the size of the ndarray in each dimension
towd_ar.shape

(2, 3)

In [86]:
#ndaarray.size  represents the total number of elements in the ndarray
towd_ar.size

6

In [87]:
#ndarray.dtype tells the data type of the elements of a Numpy array
towd_ar.dtype

dtype('int32')

In [88]:
#ndarray.itemsize returns the size(in bytes) of each element of a Numpy arry
towd_ar.itemsize

4

In [204]:
# Transpose Matrix
towd_ar.T

array([[23,  5,  3],
       [ 4,  2,  4]])

In [207]:
#Flat
towd_ar.flat

In [206]:
for i in towd_ar.flat:
    print(i)

23
4
5
2
3
4


## Type Conversion in numpy array
- tolist() is used convert array into simple list
- astype() is used for covert type

In [214]:
x=np.arange(12)
print(x)
print(type(x))
print("Array to list: ",x.tolist())
print(type(x.tolist()))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
Array to list:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
<class 'list'>


In [209]:
x=np.arange(9)
print(x)
print(x.dtype)

[0 1 2 3 4 5 6 7 8]
int32


In [210]:
#covert int32 into float64
x=x.astype('float64')
print(x)
print(x.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]
float64


# Numpy axis
* For 1D array number of axis is 1 (axis 0) *
* For 2D array number of axis is 2 (axis 0 and axis 1) *
* For  2D array 0 axis is counted for column and axis 1 is counted for row

In [79]:
z=[[1,2,3],[4,5,6],[7,1,0]]
ar=np.array(z)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [53]:
ar.sum(axis=0) #[1+4+7=12,2+5+1=8,3+6+0=9] sum of every column

array([12,  8,  9])

In [54]:
ar.sum(axis=1) # sum of every row

array([ 6, 15,  8])

# Some basic method in numpy:

- reshape() 
- resize() 
- concatenate()
- ravel()
- transpose()

In [89]:
towd_ar

array([[23,  4,  5],
       [ 2,  3,  4]])

In [90]:
towd_ar.shape

(2, 3)

In [93]:
#reshape() method
towd_ar.reshape(3,2) # change the shape into (3,2)

array([[23,  4],
       [ 5,  2],
       [ 3,  4]])

In [98]:
#resize() method
towd_ar.resize(3,2) #change the shape into (3,2) as well
towd_ar

array([[23,  4],
       [ 5,  2],
       [ 3,  4]])

#### Difference between reshape and resize method
Both ***reshape()*** and ***resize()*** method change the shape of the numpy array but the difference is that using resize() will affect the orginal array(like inplace=True) while using reshape create a new reshaped instance of the array.Examples are given below.

In [106]:
#Example for reshape() method
r=np.arange(9)
print('Orginal r: \n',r)
print('\nreshaped array: \n',r.reshape(3,3))
print('\nnarry r after reshape was applied: \n',r)

Orginal r: 
 [0 1 2 3 4 5 6 7 8]

reshaped array: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

narry r after reshape was applied: 
 [0 1 2 3 4 5 6 7 8]


In [104]:
#Example for resize() method
r=np.arange(9)
print('Orginal r: \n',r)
print('\nresized array: \n',r.resize(3,3))
print('\nnarry r after reshape was applied: \n',r)


Orginal r: 
 [0 1 2 3 4 5 6 7 8]

reshaped array: 
 None

narry r after reshape was applied: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


#### concatenate() method:
concatenate() method can be used to concatenate two arrays either row-wise or column-wise.Concatenate function can take two or more arrays of the same shape and by default it contaenates row-wise(axis=0)

In [109]:
array_1=np.arange(10,19).reshape(3,3)
array_2=np.arange(3,12).reshape(3,3)
print('array_1: \n  ',array_1)
print('\narray_2: \n  ',array_2)

array_1: 
   [[10 11 12]
 [13 14 15]
 [16 17 18]]

array_2: 
   [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [110]:
#concatenate : row-wise
np.concatenate((array_1,array_2))

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [112]:
#concatenate : column-wise
np.concatenate((array_1,array_2),axis=1)

array([[10, 11, 12,  3,  4,  5],
       [13, 14, 15,  6,  7,  8],
       [16, 17, 18,  9, 10, 11]])

## ravel() method:-
- ravel() method is used to convert 2D array into 1D array.


In [118]:
tow_d_array=np.arange(3,12).reshape(3,3)
print(tow_d_array)
print("array dimention: ",tow_d_array.ndim)




[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
array dimention:  2


In [117]:
tow_d_array.ravel()

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

### transpose() method:
- replace row elements into column and column element into row

In [120]:
r=np.arange(2,11).reshape(3,3)
r

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [121]:
r.transpose()

array([[ 2,  5,  8],
       [ 3,  6,  9],
       [ 4,  7, 10]])

## Common statistical functions in numpy:
- sum()      :used for sum
- min()      :used for finding mininum value
- max()      :used for finding maximum value
- mean()     :used for finding mean value
- median()   :used for finding median value
- std()      :used for finding standard deviation
- var()      :used for finding variance
- sort()     :used for sorting
- ptp()      :return range(max-min) of values 

In [122]:
test_ar=np.arange(3,12).reshape(3,3)

In [123]:
test_ar

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [131]:
#sum() method
print('Sum of all element: ', np.sum(test_ar)) #finding sum of all element
print('Sum of all element along axis 0: ',np.sum(test_ar,axis=0)) #sum of all element in column wise
print('Sum of all element along axis 1: ',np.sum(test_ar,axis=1)) #sum of all element in row wise

Sum of all element:  63
Sum of all element along axis 0:  [18 21 24]
Sum of all element along axis 1:  [12 21 30]


In [132]:
#min() method
print('Min value  from all the element: ', np.min(test_ar)) #finding min  value from all the element
print('Min value  along axis 0: ',np.min(test_ar,axis=0)) #finding min value in column wise
print('Min value  along axis 1: ',np.min(test_ar,axis=1)) #finding min value in row wise

Min value  from all the element:  3
Min value  along axis 0:  [3 4 5]
Min value  along axis 1:  [3 6 9]


In [133]:
#max() method
print('Max value  from all the element: ', np.max(test_ar)) #finding max  value from all the element
print('Max value  along axis 0: ',np.max(test_ar,axis=0)) #finding max value in column wise
print('Max value  along axis 1: ',np.max(test_ar,axis=1)) #finding max value in row wise

Max value  from all the element:  11
Max value  along axis 0:  [ 9 10 11]
Max value  along axis 1:  [ 5  8 11]


In [134]:
#mean() method
print('mean value  from all the element: ', np.mean(test_ar)) #finding mean  value from all the element
print('mean value  along axis 0: ',np.mean(test_ar,axis=0)) #finding mean value in column wise
print('mean value  along axis 1: ',np.mean(test_ar,axis=1)) #finding mean value in row wise

mean value  from all the element:  7.0
mean value  along axis 0:  [6. 7. 8.]
mean value  along axis 1:  [ 4.  7. 10.]


In [135]:
#median() method
print('median value  from all the element: ', np.median(test_ar)) #finding median  value from all the element
print('median value  along axis 0: ',np.median(test_ar,axis=0)) #finding median value in column wise
print('median value  along axis 1: ',np.median(test_ar,axis=1)) #finding median value in row wise

median value  from all the element:  7.0
median value  along axis 0:  [6. 7. 8.]
median value  along axis 1:  [ 4.  7. 10.]


In [136]:
#std() method
print('std value  from all the element: ', np.std(test_ar)) #finding std  value from all the element
print('std value  along axis 0: ',np.std(test_ar,axis=0)) #finding std value in column wise
print('std value  along axis 1: ',np.std(test_ar,axis=1)) #finding std value in row wise

std value  from all the element:  2.581988897471611
std value  along axis 0:  [2.44948974 2.44948974 2.44948974]
std value  along axis 1:  [0.81649658 0.81649658 0.81649658]


In [137]:
#var() method
print('var value  from all the element: ', np.var(test_ar)) #finding median  value from all the element
print('var value  along axis 0: ',np.var(test_ar,axis=0)) #finding median value in column wise
print('var value  along axis 1: ',np.var(test_ar,axis=1)) #finding median value in row wise

var value  from all the element:  6.666666666666667
var value  along axis 0:  [6. 6. 6.]
var value  along axis 1:  [0.66666667 0.66666667 0.66666667]


In [139]:
#sort() method
print('sort value  from all the element:\n', np.sort(test_ar)) #finding median  value from all the element
print('sort value  along axis 0:\n',np.sort(test_ar,axis=0)) #finding median value in column wise
print('sort value  along axis 1:\n ',np.sort(test_ar,axis=1)) #finding median value in row wise

sort value  from all the element:
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
sort value  along axis 0:
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
sort value  along axis 1:
  [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [177]:
#ptp() method
print('range(max-min) value  from all the element:\n', np.ptp(test_ar)) #finding range(max-min)   value from all the element
print('range(max-min)  value  along axis 0:\n',np.ptp(test_ar,axis=0)) #finding range(max-min)  value in column wise
print('range(max-min)  value  along axis 1:\n ',np.ptp(test_ar,axis=1)) #finding range(max-min)  value in row wise

range(max-min) value  from all the element:
 8
range(max-min)  value  along axis 0:
 [6 6 6]
range(max-min)  value  along axis 1:
  [2 2 2]


# Arithmetic Operations in Numpy

In [146]:
arr1=np.arange(10).reshape(2,5)
arr2=np.array([3,4,9,3,4])
print("Array_1: \n",arr1)
print("Array_2: \n",arr2)
#Adding two array
print('Adding two arrays: \n',arr1+arr2)
#Subtract two array
print('Subracting two arrays: \n',arr1-arr2)
#Multiply two array
print('Multiply two array: \n',arr1*arr2)
#Division
print('Division two array:\n',arr1/arr2)
#square root of an array
print('Square root of array_1 :\n',np.sqrt(arr1))

Array_1: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Array_2: 
 [3 4 9 3 4]
Adding two arrays: 
 [[ 3  5 11  6  8]
 [ 8 10 16 11 13]]
Subracting two arrays: 
 [[-3 -3 -7  0  0]
 [ 2  2 -2  5  5]]
Multiply two array: 
 [[ 0  4 18  9 16]
 [15 24 63 24 36]]
Division two array:
 [[0.         0.25       0.22222222 1.         1.        ]
 [1.66666667 1.5        0.77777778 2.66666667 2.25      ]]
Square root of array_1 :
 [[0.         1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712 3.        ]]


# Indexing
- Accessing the array element

In [151]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [215]:
x[2] #for 1D array

2

In [153]:
x[-2]

8

In [156]:
y=np.arange(15,30).reshape(3,5)
y

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [158]:
#before comma(,) indicates row range and after comma(,) indicates column range
y[1:,3:] 

array([[23, 24],
       [28, 29]])

In [166]:
y[:,3:]=50 #assign vale using indexing
y

array([[15, 16, 17, 50, 50],
       [20, 21, 22, 50, 50],
       [25, 26, 27, 50, 50]])

In [168]:
 z=np.linspace(1,10,50)

In [170]:
z[3:]=20
z

array([ 1.        ,  1.18367347,  1.36734694, 20.        , 20.        ,
       20.        , 20.        , 20.        , 20.        , 20.        ,
       20.        , 20.        , 20.        , 20.        , 20.        ,
       20.        , 20.        , 20.        , 20.        , 20.        ,
       20.        , 20.        , 20.        , 20.        , 20.        ,
       20.        , 20.        , 20.        , 20.        , 20.        ,
       20.        , 20.        , 20.        , 20.        , 20.        ,
       20.        , 20.        , 20.        , 20.        , 20.        ,
       20.        , 20.        , 20.        , 20.        , 20.        ,
       20.        , 20.        , 20.        , 20.        , 20.        ])

#  Condition of Numpy array
- np.where(conditon[,x,y]) functions returns the indices of elements in an input array where the given condition is satisfied

In [147]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [149]:
print('Indices of elements <4')
b=np.where(a<4)
print(b)
print('Elements which ar <4')
print(a[b])

Indices of elements <4
(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64))
Elements which ar <4
[1 2 3]


**For more check out the numpy documentation**
<a href="https://www.numpy.org/">numpy documentation</a>